version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: smartmealplanner-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: mealplanner

volumes:
  mongo-data:
